// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU8tHpvsv7y5kbJYognJcVXzuT7gIzvUg',
    appId: '1:304042370688:web:af4f7d3743d8cc0b9da865',
    messagingSenderId: '304042370688',
    projectId: 'evently-app-1ec56',
    authDomain: 'evently-app-1ec56.firebaseapp.com',
    storageBucket: 'evently-app-1ec56.firebasestorage.app',
    measurementId: 'G-8R6DS2M5XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1hnTSTdbi8TOYrPNp-s2SEkJf6eEwnKk',
    appId: '1:304042370688:android:b5b4a5accceec5fc9da865',
    messagingSenderId: '304042370688',
    projectId: 'evently-app-1ec56',
    storageBucket: 'evently-app-1ec56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAQzDT_jgDSraAkK4kyAXthUZmcjCPDTc',
    appId: '1:304042370688:ios:7c12e9dc7953b2369da865',
    messagingSenderId: '304042370688',
    projectId: 'evently-app-1ec56',
    storageBucket: 'evently-app-1ec56.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAQzDT_jgDSraAkK4kyAXthUZmcjCPDTc',
    appId: '1:304042370688:ios:7c12e9dc7953b2369da865',
    messagingSenderId: '304042370688',
    projectId: 'evently-app-1ec56',
    storageBucket: 'evently-app-1ec56.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU8tHpvsv7y5kbJYognJcVXzuT7gIzvUg',
    appId: '1:304042370688:web:a22a56bf2f2a91e09da865',
    messagingSenderId: '304042370688',
    projectId: 'evently-app-1ec56',
    authDomain: 'evently-app-1ec56.firebaseapp.com',
    storageBucket: 'evently-app-1ec56.firebasestorage.app',
    measurementId: 'G-6XM44CMN3S',
  );
}
